### ISSUE TITLE
下载《我喜欢的音乐》歌单时报错

### ISSUE THREAD

**Issue by xzsk2** [mos9527/pyncm#20]
```
# pyncm --load .pyncm "https://music.163.com/playlist\?id\=*********"

[WARN] coloredlogs 没有安装，日志不会以彩色输出
[INFO] pyncm.main 读取登录信息 : .pyncm
[INFO] pyncm.main 处理任务 ID: ********* 类型: 歌单®
[INFO] pyncm.main 歌单 ：****喜欢的音乐
[ERRO] pyncm.api Response is not valid JSON : Extra data: line 1 column 26 (char 25)
Traceback (most recent call last):
  File "/home/sakari/.local/bin/pyncm", line 8, in <module>
    sys.exit(__main__())
  File "/home/sakari/.local/lib/python3.10/site-packages/pyncm/__main__.py", line 510, in __main__
    total_queued += subroutine(ids)  # Enqueue tasks
  File "/home/sakari/.local/lib/python3.10/site-packages/pyncm/__main__.py", line 323, in __call__
    queued += self.forIds(
  File "/home/sakari/.local/lib/python3.10/site-packages/pyncm/__main__.py", line 272, in forIds
    dDetails = track.GetTrackDetail(ids).get("songs")
AttributeError: 'Response' object has no attribute 'get'
```

尝试过 `pyncm --phone --pwd --save` 和 `demos/手机登录.py` 生成的 session，均为以上报错

**Comment by mos9527** [comment]
我用自己的账号试了下，没有重现
能加上 `--log-level DEBUG` 发下日志吗?

**Comment by xzsk2** [comment]
https://pastebin.com/cgqtUue4

里面三千多首歌，或许是太多了?

**Comment by mos9527** [comment]
网易那边好像会在歌曲数>1000时把query丢掉
1.6.7.3会尝试把歌单ID分块处理，能再试试看吗?

**Comment by xzsk2** [comment]
1.6.7.3 可以了！😀
