### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by z0z0r4** [mos9527/pyncm#42]
```
PS C:\Users\DELL> pyncm https://music.163.com/#/artist?id=1064078 --phone  --pwd 
2023-06-23 23:45:09 pyncm.main [INFO] 账号 ：z0z0r4 (VIP 0)
2023-06-23 23:45:09 pyncm.main [INFO] 处理任务 ID: 1064078 类型: 艺术家
2023-06-23 23:45:09 pyncm.main [INFO] 艺术家：Xeuphoria
0.00B: 0.0%|                                                                                           | 0.00/0 00:00<?Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Python\Python311\Scripts\pyncm.exe\__main__.py", line 7, in <module>
  File "D:\Python\Python311\Lib\site-packages\pyncm\__main__.py", line 700, in __main__
    logger.info(f'任务完成率 {(executor.finished_tasks * 100 / len(queuedTasks)):.1f}%')
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
0.00B: 0.0%|
```

**Comment by z0z0r4** [comment]
用户下载都失效了
