### ISSUE TITLE
匿名登陆失败

### ISSUE THREAD

**Issue by Aalivexy** [mos9527/pyncm#45]
新版本，新问题.jpg
旧版本可以正常匿名登陆，新版本会登陆失败
嗯，旧版本是没问题的

旧版本 https://github.com/mos9527/pyncm/releases/tag/1.6.9.1
```
> pyncm "https://music.163.com/#/song?id=1882642256"
2023-08-09 11:45:54 pyncm.main [INFO] 以匿名身份登陆成功，deviceId=dgGOOGgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, UID: 8762336087
2023-08-09 11:45:54 pyncm.main [INFO] 处理任务 ID: 1882642256 类型: 单曲
2023-08-09 11:45:54 pyncm.main [INFO] 开始下载 #1 / 1 - Oracle - 黄霄雲,HOYO-MiX - Oracle - 128kbps - MP3
2023-08-09 11:45:55 pyncm.main [INFO] 完成下载 #1 / 1 - Oracle - 黄霄雲,HOYO-MiX
2023-08-09 11:45:55 pyncm.main [INFO] 任务完成率 100.0%
5.31MB: 100.0%|███████████████████████████████████████████████████████████████████████████████████▉| 1.00/1 00:01<00:00
```

新版本 https://github.com/mos9527/pyncm/releases/tag/1.6.9.3
```
> pyncm "https://music.163.com/#/song?id=1882642256"
Traceback (most recent call last):
  File "pyncm\__main__.py", line 763, in <module>
  File "pyncm\__main__.py", line 679, in __main__
  File "pyncm\apis\login.py", line 285, in LoginViaAnonymousAccount
AssertionError: 匿名登陆失败
[29476] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by Aalivexy** [comment]
也许是因为这个：

https://github.com/mos9527/pyncm/commit/1ba75618acaebd8815fb2a6dfb17f77308648a77#diff-ea9093d8f969f74bcf7a829ddbf432041f5fa265dba21b13df50c6b00b93c371R663

**Comment by Aalivexy** [comment]
问题已定位：
https://github.com/mos9527/pyncm/compare/1.6.9.1...1.6.9.2#diff-ea9093d8f969f74bcf7a829ddbf432041f5fa265dba21b13df50c6b00b93c371R675

`deviceId` 似乎不应该取 `[:10]`？

**Comment by mos9527** [comment]
目前也没找到`deviceId`取值和匿名能否登录的相关性
已知的是某些ID可用，比如`pyncm!`
有时间我再看看官方的impl，不过暂时就通过`--deviceId`用一个可用的id代替吧
（已经在TODO上了还没修

**Comment by mos9527** [comment]
写了个fuzzer发现随机选取的`deviceId`逼近50%登陆成功率
![image](https://github.com/mos9527/pyncm/assets/31397301/894acc34-7c7f-4275-8d4c-69a3b156c41f)
fuzzer在这里，可以自己跑跑看
```python
import sys
from pyncm.apis.login import LoginViaAnonymousAccount
from pyncm import GetCurrentSession
from pyncm.utils import RandomString
BASE16 = '0123456789ABCDEF'
good = total = 0
while True:
    try:
        total += 1
        GetCurrentSession().deviceId = RandomString(52,BASE16)
        deviceId = GetCurrentSession().deviceId
        LoginViaAnonymousAccount()        
        good += 1
        open('private.good.deviceIds.txt','+a').writelines([deviceId + '\n'])        
    except AssertionError as e:        
        pass
    except KeyboardInterrupt:
        sys.exit(1)
    print(f'RATE/{(100*good/total):.2f}% ITER/{total}             ',end='\r')
```
不过就为什么决定还是不深究了
[`1.6.9.4`](https://github.com/mos9527/pyncm/commit/21177d044ba380f86e86b1f7dc40186ca32ad429)开始默认使用随机抽样可用ID直接登陆，目前fuzz说明如此匿名登陆一定能成功
同时截取deviceId就没做了；长度和成功率貌似仍然无关（同样在50%！）
姑且这样吧。最近没太多力气弄逆向了😥
