### ISSUE TITLE
登陆失败，提示当前登录存在安全风险，请稍后再试

### ISSUE THREAD

**Issue by jiezaizone** [mos9527/pyncm#51]
root@DS220plus:/volume1/music/download-test# pyncm --phone xxx --pwd xxx --save /volume1/music/download-test/.pyncm --deviceId 120
Traceback (most recent call last):
  File "/bin/pyncm", line 8, in <module>
    sys.exit(__main__())
  File "/usr/lib/python3.8/site-packages/pyncm/__main__.py", line 677, in __main__
    login.LoginViaCellphone(args.phone, args.pwd)
  File "/usr/lib/python3.8/site-packages/pyncm/apis/login.py", line 152, in LoginViaCellphone
    WriteLoginInfo(login_status)
  File "/usr/lib/python3.8/site-packages/pyncm/apis/login.py", line 29, in WriteLoginInfo
    raise LoginFailedException(sess.login_info["content"])
pyncm.apis.LoginFailedException: {'loginType': 1, 'code': 10004, 'message': '当前登录存在安全风险，请稍后再试', 'redirectUrl': 'https://st.music.163.com/st/user-new/phoneReuse/index.html?scene=-1&userId=1555728631&failCode=10003&systemOs=pc&ts=1700553055858&NMSCVT=-2011112894'}

**Comment by Starlight-cn** [comment]
+1

**Comment by palachute** [comment]
请问解决了吗

**Comment by mos9527** [comment]
试试看 [1.6.12](https://github.com/mos9527/pyncm/commit/eb9b887fcfdb0755bbf3d99fe40cfd74387141af)

**Comment by hyx0329** [comment]
个人测试，原1.6.11提示安全风险，1.6.12已可正常登陆
