### ISSUE TITLE
使用`--no-overwrite`跳过既有歌曲会使`task.extension`不存在导致`--save-m3u`时出错

### ISSUE THREAD

**Issue by hyx0329** [mos9527/pyncm#57]
看起来在没下载歌曲时不会定义`extension`这个属性，而恰好在保存m3u时需要这个。版本1.6.13，使用pipx安装。

```
Traceback (most recent call last):
  File "/home/user/.local/bin/pyncm", line 8, in <module>
    sys.exit(__main__())
             ^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/pyncm/lib/python3.11/site-packages/pyncm/__main__.py", line 755, in __main__
    filePath = task.save_as + '.' + task.extension
                                    ^^^^^^^^^^^^^^
AttributeError: 'TrackDownloadTask' object has no attribute 'extension'
```

**Comment by hyx0329** [comment]
已确认1.6.14修复了此问题
