### ISSUE TITLE
java创建pyncm子进程报错

### ISSUE THREAD

**Issue by xzxzhixin** [mos9527/pyncm#62]
我使用java创建子进程
使用的java代码是cn.hutool.core.util.RuntimeUtil.exec(cmds)
这个cmds的值是[E:\wangYiYunXiaZai\pyncm.exe, --http, --load, E:\wangYiYunXiaZai\pyncmInfoSave.save, --lyric-no, none, -m, 4, --no-overwrite, --output, E:/myService/windows-amd64-filebrowser/fileBrowserData/音乐, --quality, standard, "playlist=10055287548"]

结果得到报错信息是：
Traceback (most recent call last):
File "pyncm\__main__.py", line 767, in <module>
File "pyncm\__main__.py", line 695, in __main__
File "pyncm\__main__.py", line 403, in __call__
ValueError: dictionary update sequence element #0 has length 128; 2 is required

我直接在cmd里面执行上面命令不会报这个报错，反而是正确执行完

**Comment by xzxzhixin** [comment]
就是昨天（2024年8月20日）网易云崩了就这样了
