### ISSUE TITLE
以命令行方式登录失败

### ISSUE THREAD

**Issue by shikkoku** [mos9527/pyncm#67]
`pyncm --phone --pwd  --save .\.config\pyncm\id.txt`

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\feiyu\AppData\Roaming\Python\Python311\Scripts\pyncm.exe\__main__.py", line 7, in <module>
  File "C:\Users\feiyu\AppData\Roaming\Python\Python311\site-packages\pyncm\__main__.py", line 791, in __main__
    login.LoginViaCellphone(args.phone, args.pwd)
  File "C:\Users\feiyu\AppData\Roaming\Python\Python311\site-packages\pyncm\apis\login.py", line 160, in LoginViaCellphone
    WriteLoginInfo(login_status, session)
  File "C:\Users\feiyu\AppData\Roaming\Python\Python311\site-packages\pyncm\apis\login.py", line 28, in WriteLoginInfo
    raise LoginFailedException(session.login_info["content"])
pyncm.apis.LoginFailedException: {'code': -460, 'message': '网络太拥挤，请稍候再试！'}`

命令行方式有其他登录方式吗？

**Comment by mos9527** [comment]
>  {'code': -460, 'message': '网络太拥挤，请稍候再试！'}

[1.6.18](https://github.com/mos9527/pyncm/commit/19a7ea405e5914088af51243c909520f4036713c) 更新了登录config, 该错误经测试暂时得到缓解

> 命令行方式有其他登录方式吗？

命令行不计划提供手机登录以外的登陆方式，不过同时[Demos](https://github.com/mos9527/pyncm/tree/master/demos)中提供了**二维码登录**和**邮箱登录**的方案；其产生的Session串可存为文本文档后使用`--load`加载以等效登录

**Comment by mos9527** [comment]
https://github.com/mos9527/pyncm/issues/68#issuecomment-2482776635
